const fs = require('fs');

const stores = JSON.parse(fs.readFileSync('C:/Users/Supreme_Traders/.gemini/antigravity/scratch/all_repos/my-coupon/recent_stores.json', 'utf8'));

// Domain mapping based on store slug and brand name
function getRealDomain(store) {
  const slug = store.slug;
  const name = store.name.toLowerCase();

  // Known brand domains
  const domainMap = {
    'underoutfit': 'underoutfit.com',
    'youngla': 'youngla.com',
    'inner-light-sauna': 'innerlightsauna.com',
    'capezio': 'capezio.com',
    'gray-nicolls': 'gray-nicolls.co.uk',
    'freda-salvador': 'fredasalvador.com',
    'boroux': 'boroux.com',
    'the-belly-lab': 'thebellylab.com',
    'minoston': 'minoston.com',
    'reima-us': 'reima.com',
    'voyage-prive-it': 'voyage-prive.com',
    'psprint-us': 'psprint.com',
    'perricone-md-us': 'perriconemd.com',
    'dreampairs-us': 'dreampairshoes.com',
    'maxpeedingrods-us': 'maxpeedingrods.com',
    'nanobag-us': 'nanobag.com',
    'jade-leaf-matcha': 'jadeleafmatcha.com',
    'bruno-marc-us': 'brunomarcshoes.com',
    'pupper-crust': 'pupper-crust.com',
    'artextured': 'artextured.com',
    'walabot-us': 'walabot.com',
    'shoes-fr': 'shoes.fr',
    'jansport-us': 'jansport.com',
    'megawheels-us': 'megawheels.com',
    'glowria': 'glowria.fr',
    'sport-service': 'sportservice.com',
    'fantastic-services': 'fantasticservices.com',
    'comix-panini-it': 'panini.it',
    'serwall-outdoor-us': 'serwall.com',
    'patricia-nash-us': 'patricianashdesigns.com',
    'bmimd': 'bmimd.com',
    'cosyneo': 'cosyneo.com',
    'quicksilver': 'quiksilver.com',
    'blokees': 'blokees.com',
    'ozmoz': 'ozmoz.com',
    'irislee-gallery': 'irisleegallery.com',
    'veise': 'veise.com',
    'cocokind-us': 'cocokind.com',
    'aulumu-us': 'aulumu.com',
    'oufer-body-jewelry': 'ouferbodyjewelry.com',
    'laurence-boutique': 'laurenceboutique.com',
    'fuumuui': 'fuumuui.com',
    'irockersup': 'irockersup.com',
    'bagsmart-us': 'bagsmart.com',
    'parc-asterix': 'parcasterix.fr',
    'don-t-buy-her-flowers': 'dontbuyherflowers.com',
    'ptlom': 'ptlom.com',
    'thread-wallets-us': 'threadwallets.com',
    'young-electric': 'youngelectricbikes.com',
    'alfaram': 'alfaram.com',
    'opticas-lux': 'lux.mx',
    'acousart': 'acousart.com',
    'pai-technology-inc': 'pai.technology',
    'eric-favre-cpa': 'ericfavre.com',
    'mousse-et-coussins': 'mousseetcoussins.com',
    'dreamcloud': 'dreamcloudsleep.com',
    'walking-pad': 'walkingpad.com',
    'omfort': 'omfort.com',
    'navimow': 'navimow.segway.com',
    'naturnest-us-uk': 'naturnest.com',
    'bodega': 'bdgastore.com',
    'nordictrack': 'nordictrack.com',
    'professional-supplement-center': 'professionalsupplementcenter.com',
    'jennibag': 'jennibag.com',
    'anastasia-beverly-hills': 'anastasiabeverlyhills.com',
    'neo-sabers': 'neosabers.com',
    'rebecca-minkoff': 'rebeccaminkoff.com',
    'mobapad': 'mobapad.com',
    'puckipuppy-us': 'puckipuppy.com',
    'silver-jeans': 'silverjeans.com',
    'bond-mason': 'bondmason.com',
    'harlembling': 'harlembling.com',
    'qidi': 'qidi3d.com',
    'hunter-fan': 'hunterfan.com',
    'charles-bentley': 'charlesbentley.com',
    'celestyal-cruise': 'celestyal.com',
    'sublue': 'sublue.com',
    'apolosign': 'apolosign.com',
    'coutr': 'coutr.com',
    'piedmontese': 'piedmontese.com',
    'zulay-kitchen': 'zulaykitchen.com',
    'salt-life': 'saltlife.com',
    'blue-seventy': 'blueseventy.com',
    'dashing-diva': 'dashingdiva.com',
    'steve-madden': 'stevemadden.com',
    'lazyone': 'lazyone.com',
    'dermalogica': 'dermalogica.com',
    'la-mer': 'cremedelamer.com',
    'hyperice': 'hyperice.com',
    'sanfer-bike': 'sanferbike.com',
    'nexbelt': 'nexbelt.com',
    'tuft-needle': 'tuftandneedle.com',
    'outdoor-gear-exchange': 'gearx.com',
    'swolverine': 'swolverine.com',
    'cosabella': 'cosabella.com',
    'frost-buddy': 'frostbuddy.com',
    'seagate': 'seagate.com',
    'american-giant': 'american-giant.com',
    'parasol': 'parasolco.com',
    'double-oak-essentials': 'doubleoakessentials.com',
    'rockbros': 'rockbros.com',
    'ballboyz': 'ballboyz.com',
    'ohora': 'ohora.com',
    'kittyspout': 'kittyspout.com',
    'sneaxx': 'sneaxx.com',
    'showpo': 'showpo.com',
    'brunt': 'bruntworkwear.com',
    'the-double-f': 'thedoublef.com',
    'democracy-clothing': 'democracyclothing.com',
    'magpul': 'magpul.com',
    'eileen-fisher': 'eileenfisher.com',
    'solo-stove': 'solostove.com',
    'aldo': 'aldoshoes.com',
    'antler-uk': 'antler.co.uk',
    'nantahala-outdoor-center': 'noc.com',
    'brightmeds': 'brightmeds.com',
    'evereden-us': 'evereden.com',
    'cosset': 'cossetwellness.com',
    'abacus-sportswear': 'abacussportswearus.com',
    'pure-bio-labs': 'purebiolabs.com',
    'enjoy-the-wood': 'enjoythewood.com',
    'aecojoy': 'aecojoy.com',
    'strike-nutrition': 'strikenutrition.com',
    'it-just-works-deodorant': 'itjustworksdeodorant.com',
    'level': 'level.co',
    'nikola-toy': 'nikolatoy.com',
    'alpha-gear': 'alphagear.com',
    'avio-travel-us': 'aviotravel.com',
    'parfait-lingerie': 'parfaitlingerie.com',
    'amyet-bikes': 'amyetebikes.com',
    'burneek': 'burneek.com',
    'zero-waste-store': 'zerowastestore.com',
    'venalisa': 'venalisa.com',
    'bosshorn': 'bosshorn.com',
    'pongbot': 'pongbotstar.com',
    'acrtmatic': 'acrtmatic.com',
    'bulletproof-fitness-equipment-us': 'bulletproofft.com',
    'mirai-clinical-us': 'miraiclinical.com',
    'octobuddy-us': 'octobuddy.com',
    'waterdrop': 'waterdropfilter.com',
    'ohmmu': 'ohmmu.com',
    'dc-house': 'dchouse.com',
    'jiaro-pack': 'jiaropack.com',
    'fuji-sports': 'fujisports.com',
    'badlands-gear-us': 'badlandsgear.com',
    'buy-larine-u': 'buylarine.com',
    'roto-rooter': 'rotorooter.com',
    'wjs-home': 'wjshome.com',
    'meshy-ai': 'meshy.ai',
    'tous': 'tous.com',
    'pop-ups-brand': 'popupsbrand.com',
    'love-in-faith': 'loveinfaith.life',
    'lumai-br': 'lumaibr.com',
    'silkiee': 'silkiee.com',
    'pretty-strap': 'prettystrap.com',
    'desktronic-se': 'desktronic.se',
    'monument-grills': 'monumentgrills.com',
    'origo-shoes': 'origoshoes.com',
    'javvy-coffee': 'javvycoffee.com',
    'redu-sculpt': 'redusculpt.com',
    'desktronic': 'desktronic.com',
    'proactiv': 'proactiv.com',
    'atoto': 'myatoto.com',
    'little-links-golf': 'littlelinksgolf.com',
    'filter-baby': 'filterbaby.com',
    'tarkine-au': 'tarkine.com',
    'lumibricks': 'lumibricks.com',
    'quickplay': 'quickplaysport.us',
    'invisawear': 'invisawear.com',
    'anti-apex': 'antiapex.com',
    'elegant-shower': 'elegantshowers.co.uk',
    'comfrt': 'comfrt.com',
    'soldiers-nutrition': 'soldiersnutrition.com',
    'lovat-parks': 'lovatparks.com',
    'paddle-pro': 'paddlepro.com',
    'joroto': 'jorotofitness.com',
    'patioliving': 'patioliving.com',
    'miele': 'mieleusa.com',
    'sperry-us': 'sperry.com',
    'aerotel': 'myaerotel.com',
    'im': 'the-tls.co.uk',
    'wiley-x': 'wileyx.com',
    'florsheim': 'florsheim.com',
    'viviscal': 'viviscal.com',
    'sealy': 'sealy.com',
    'shelly': 'shelly.com',
    'park-sleep-fly': 'parksleepfly.com',
    'xero-shoes': 'xeroshoes.com',
    'overstock': 'overstock.com',
    'eagle-creek': 'eaglecreek.com'
  };

  if (domainMap[slug]) return domainMap[slug];

  // Try extracting from website URL if clean
  if (store.website) {
    const match = store.website.match(/url=https?%3A%2F%2F([^%&\s\/]+)/);
    if (match) {
      const d = match[1].toLowerCase().replace(/^www\./, '');
      return d;
    }
  }

  return slug.replace(/-us$|-uk$|-ca$|-it$|-se$|-fr$|-au$|-br$/g, '') + '.com';
}

console.log('Mapping domains for all', stores.length, 'stores...');
const mapped = stores.map(s => ({
  id: s.id,
  name: s.name,
  slug: s.slug,
  domain: getRealDomain(s)
}));

fs.writeFileSync('C:/Users/Supreme_Traders/.gemini/antigravity/scratch/all_repos/my-coupon/store_domains.json', JSON.stringify(mapped, null, 2));
console.log('Saved mapped domains to store_domains.json');
